name: Android CI

on:
  push:
    branches:
      - main
    tags:
      - 'testing*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Add execute permission to gradlew
        run: chmod u+x ./gradlew
      - name: Assemble debug apk
        run: |
          ./gradlew assembleDebug
          # Add timestamp to the debug APK
          timestamp=$(date "+%Y%m%d%H%M%S")
          mv app/build/outputs/apk/debug/app-debug.apk app/build/outputs/apk/debug/app-debug-${timestamp}-unsigned.apk
      - name: Run tests
        run: ./gradlew test
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/
      - name: Create or Update Release
        id: create_or_update_release
        uses: softprops/action-gh-release@v1
        with:
          files: app/build/outputs/apk/debug/app-debug-${timestamp}-unsigned.apk
        env:
          GITHUB_TOKEN: ${{ secrets.TOKENTOKEN }}
